# Generated by Django 4.2.2 on 2023-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_featured_img_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='remarks',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
