# Generated by Django 4.2.2 on 2023-07-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_detail_alter_category_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
