# Generated by Django 4.2.2 on 2023-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profile_imgs/'),
        ),
    ]
