# Generated by Django 4.2.2 on 2023-08-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name_plural': '7 .Student Favorite Courses',
            },
        ),
    ]
