# Generated by Django 4.2.2 on 2023-08-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studentfavoritecourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfavoritecourse',
            old_name='Student',
            new_name='student',
        ),
    ]
