# Generated by Django 4.2.2 on 2023-07-14 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_featured_img_category_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
