# Generated by Django 4.2.2 on 2023-07-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_imgs/'),
        ),
    ]
