# Generated by Django 4.2.2 on 2023-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_student_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='chapter_material/'),
        ),
    ]
