# Generated by Django 4.2.2 on 2023-07-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_options_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='featured_img',
            new_name='video',
        ),
    ]
