# Generated by Django 4.2.2 on 2023-07-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_category_category_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
